In [1]:
import numpy as np
import pandas as pd
from flask import request

In [2]:
Data=pd.read_csv('Bank_Authentication.csv')

In [3]:
Data.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
Data

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [5]:
X=Data.drop('class',axis=1)
y=Data['class']

In [6]:
X.head()

variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [7]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
Classifier=RandomForestClassifier()
Classifier.fit(X_train,y_train)

RandomForestClassifier()

In [12]:
y_pred=Classifier.predict(X_test)

In [13]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [15]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[191   0]
 [  2 150]]
0.9941690962099126
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       191
           1       1.00      0.99      0.99       152

    accuracy                           0.99       343
   macro avg       0.99      0.99      0.99       343
weighted avg       0.99      0.99      0.99       343



In [16]:
import pickle
Pickle_Out=open('Bank_Note.pkl','wb')

In [17]:
pickle.dump(Classifier,Pickle_Out)
Pickle_Out.close()

In [18]:
Classifier.predict([[3.6216,8.666,-2.8073,-0.44699]])

array([0], dtype=int64)

In [19]:
Classifier.predict([[-1.38870,-4.87730,6.4774,0.34179]])

array([1], dtype=int64)

In [20]:
Pickle_In=open('Bank_Note.pkl','rb')
Classifier=pickle.load(Pickle_In)

In [21]:
List=Classifier.predict([[0,11,1,0]])

In [22]:
List

array([0], dtype=int64)

In [23]:
int(List)

0

In [24]:
Data1=pd.read_csv('Test_Bank.csv')

In [25]:
Data1

variance  skewness  curtosis  entropy
0   3.62160   8.66610  -2.80730 -0.44699
1   4.54590   8.16740  -2.45860 -1.46210
2   3.86600  -2.63830   1.92420  0.10645
3   3.45660   9.52280  -4.01120 -3.59440
4  -0.47465  -4.34960   1.99010  0.75170
5   1.05520   1.18570  -2.64110  0.11033
6   1.16440   3.80950  -4.94080 -4.09090
7  -4.47790   7.37080  -0.31218 -6.77540
8  -2.73380   0.45523   2.43910  0.21766